cclib/cclib-data

regression.py

This is just to get the regression code working after reorganizing tests in cclib.

Adjust regression.py to recent changes in cclib tests

---

DALTON/DALTON-2013/C_bigbasis.aug-cc-pCVQZ.out
DALTON/DALTON-2013/dvb_sp_hf_nosym.out
README.md
regression.py
regressionfiles.txt

This is related to cclib/cclib#198 and in particular 61c3760 will need to be merged in for that to pass regression tests.

Some leftovers from work on DALTON

---

GAMESS/Firefly8.0/h2o.log
regression.py
regressionfiles.txt

See cclib/cclib#208 and http://sourceforge.net/p/cclib/mailman/message/34423568/ for some context.

Add regression file from Alexis Otero-Calvis (cclib/cclib#208)

---

regression.py
regressionfiles.txt

Files moved from cclib/cclib#235.

Gaussian09: add 2D potential energy scan regressions

---

QChem/QChem4.2/opt_ZZZZ_+1.000.out

Parser fix in https://github.com/cclib/cclib/pull/269.

Q-Chem: fix for '****' in geometry optimizations

---

regression.py
regressionfiles.txt

Test for issue https://github.com/cclib/cclib/issues/150, with features implemented in https://github.com/cclib/cclib/pull/286.
This will fail without the feature PR going in first.

test Molpro2008/ch2o_molpro_casscf.out

---

QChem/QChem4.3/R_propylene_oxide_force_ccsd.out
QChem/QChem4.3/R_propylene_oxide_force_hf_numerical_energies.out
QChem/QChem4.3/R_propylene_oxide_force_mp2.out
QChem/QChem4.3/R_propylene_oxide_force_rimp2.out
QChem/QChem4.3/R_propylene_oxide_freq_ccsd.out
QChem/QChem4.3/R_propylene_oxide_freq_hf_numerical_gradients.out
QChem/QChem4.3/R_propylene_oxide_freq_mp2.out
QChem/QChem4.3/R_propylene_oxide_freq_rimp2.out
regression.py
regressionfiles.txt

https://github.com/cclib/cclib/pull/297 will need to be merged first for these to pass.

Q-Chem: parse gradients/Hessians from correlated calculations

---

NWChem/NWChem6.0/hydrogen_atom_ROHF_cc-pVDZ.out
regression.py
regressionfiles.txt

This will require https://github.com/cclib/cclib/pull/304.

Updates for ROHF

---

regression.py

Should be merged after Sanjeed's CJSON reader changes that will include the move.

Adjust regression script to move of ccio.py

---

regression.py

Uses the file from https://github.com/cclib/cclib-data/pull/30 to ensure https://github.com/cclib/cclib/issues/261 won't happen again.

Ensure moments are parsed for Gaussian

---

ORCA/ORCA3.0/skattejag.out
regressionfiles.txt

From https://github.com/cclib/cclib/issues/327.

ORCA: parsing extended energies

---

.gitignore
QChem/QChem4.4/Trp_polar_ideriv0.out
QChem/QChem4.4/Trp_polar_ideriv1.out
QChem/QChem4.4/Trp_polar_response.out
QChem/QChem4.4/full_2.out
regression.py
regressionfiles.txt

This should be merged *after* PR https://github.com/cclib/cclib/pull/359.

QChem: new section for polarizabilities

---

ORCA/ORCA4.0/1-ttt_td.out
regression.py
regressionfiles.txt

This should be merged __after__ https://github.com/cclib/cclib/pull/374.

ORCA: no etsyms from TDDFT calculation

---

DALTON/DALTON-2016/huge_neg_polar_freq.out
DALTON/DALTON-2016/huge_neg_polar_stat.out
regression.py
regressionfiles.txt

and multiple polarizabilities in one job.
Regression tests for https://github.com/cclib/cclib/pull/380.

DALTON: missing space between polarizability tensor elements

---

regression.py

The main PR is https://github.com/cclib/cclib/pull/392. This needs to go in for the main PR to pass Travis.

Changes requires for point group detection.

---

regression.py

This works in conjunction with cclib/cclib#403. Orca uses different masses for atoms.

Updates regressions for Orca molecularmass.

---

ORCA/ORCA3.0/chelpg.out
regression.py
regressionfiles.txt

@berquist I can't get the tests to run locally, but I think this should work?

added ORCA chelpg regression test

---

regression.py

This is needed for cclib/cclib#417 and needs to go in first.

Plumb through datatype from test classes to parser objects

---

DALTON/DALTON-2016/Trp_polar_response_diplnx.out
regression.py
regressionfiles.txt

Regression test for https://github.com/cclib/cclib/issues/420

DALTON: Parsing an incomplete polarizability tensor

---

regressionfiles.txt

This is the file that was attached in cclib/cclib#360

Add regression for Gaussian IRC fix

---

ORCA/ORCA4.0/CO2_freqs.out
regression.py
regressionfiles.txt

Linear molecules have `3*N - 5` modes (not `3*N - 6` modes).

Adds linear molecule test case for ORCA.

---

regressionfiles.txt

File from https://github.com/cclib/cclib/issues/430. Don't merge until fixed.

Add ADF TDDFT file that suffers from StopIteration

---

QChem/QChem5.0/argon.out
regressionfiles.txt

This needs to go in after https://github.com/cclib/cclib/pull/434.

Q-Chem: updated printing in RPA/CIS output

---

Psi/Psi4.0/water_fdgrad.out
regressionfiles.txt

Adds a regression test for parsing gradients obtained by finite difference, see cclib/cclib#464

Adds Psi4 finite difference gradient extraction test

---

regressionfiles.txt

Main PR is https://github.com/cclib/cclib/pull/516.

typos: Molacs -> Molcas

---

Gaussian/Gaussian09/relaxed_PES_testCO2.log
Gaussian/Gaussian09/relaxed_PES_testH2.log
regressionfiles.txt

These are files that were attached to cclib/cclib#211

Add regression for Gaussian09 relaxed scans

---

ORCA/ORCA4.0/H2-_CASSCF_opt.out
regressionfiles.txt

Adds Orca CASSCF optimization regression.

---

ORCA/ORCA4.0/650.out
regressionfiles.txt

Output from https://github.com/cclib/cclib/issues/650.
This needs to go in _after_ https://github.com/cclib/cclib/pull/651.

ORCA: output that has malformed input section

---

Gaussian/Gaussian98/NIST_CCCBDB_1himidaz_m21b0.out
regressionfiles.txt

The file is the same as https://github.com/ccdata/nist-cccbdb/blob/master/1himidaz/m21b0.out

Add Gaussian98 G3 job from NIST CCCBDB suite

---

DALTON/DALTON-2018/dft_properties_nosym_H2O_cc-pVDZ.out
regressionfiles.txt

The file for https://github.com/cclib/cclib/issues/667 and https://github.com/cclib/cclib/pull/668.
This needs to go in **after** https://github.com/cclib/cclib/pull/668.

DALTON: add regression test for development version parsing

---

QChem/QChem4.4/678.out
regressionfiles.txt

This file was provided in https://github.com/cclib/cclib/issues/678.
This PR should go in **after** https://github.com/cclib/cclib/pull/679.

QChem: job with indeterminate symmetry for some alpha/beta MOs

---

Gaussian/Gaussian16/naturalspinorbitals_parsing.log
regressionfiles.txt

Add data for a regression test for natural spin orbital parsing.

Add Natural Spin Orbital parsing data

---

ORCA/ORCA4.0/hydrogen_fluoride_numfreq.out
ORCA/ORCA4.0/hydrogen_fluoride_usesym_anfreq.out
regressionfiles.txt

Regression files for https://github.com/cclib/cclib/issues/426.

ORCA: linear C_infv molecules that didn't have vibfreqs parsed properly

---

ORCA/ORCA4.1/725.out
regressionfiles.txt

This is the regression file given in https://github.com/cclib/cclib/issues/725 fixed by https://github.com/cclib/cclib/pull/726.

ORCA: file containing embedding potentials

---

ORCA/ORCA4.1/raw_failed_run_from_issue_426.out
regressionfiles.txt

This file is from cclib/cclib#426.

Add ORCA regression file that terminated prematurely

---

ORCA/ORCA4.1/orca_from_issue_736.out
regressionfiles.txt

This is for cclib/cclib#736. Needs to go in before cclib/cclib#738.

ORCA: logfile donated

---

regressionfiles.txt

This is from cclib/cclib#740 - corresponding regression test is in cclib/cclib#741.

Add regression file cclib/cclib#740

---

Gaussian/Gaussian16/output.txt.issue754.log
regressionfiles.txt

[Gaussian] Add output.txt from cclib/cclib#754

---

regressionfiles.txt

Output file from [cclib/cclib#804](https://github.com/cclib/cclib/pull/804).

Long ORCA input from cclib/cclib#804

---

ORCA/ORCA4.1/single_atom_freq.out
regressionfiles.txt

This is the file for cclib/cclib#813 and cclib/cclib#778.

ORCA: add frequency calculation with single atom

---

ORCA/ORCA4.2/water_dlpno_ccsd.out

Not really a regression, just a kind of calculation we should be able to parse that we don't necessarily want to add as a unit test yet.
This PR should go in before https://github.com/cclib/cclib/pull/840.

ORCA: add DLPNO-CCSD calculation

---

QChem/QChem5.3/ccman2_soc_cisd.out
regressionfiles.txt

This PR should go in after https://github.com/cclib/cclib/pull/831.

QChem: add file with atomcoords in bohr

---

regressionfiles.txt

Forgot this as part of https://github.com/cclib/cclib-data/pull/128.

Add line in regressionfiles.txt for ORCA DLPNO-CCSD file

---

regressionfiles.txt

This needs to wait until cclib/cclib#857 is merged in.

Gaussian: Adding logfile from issue cclib/cclib#756

---

MOPAC/MOPAC2016/fa_from_issue_763.out
regressionfiles.txt

This is the file from cclib/cclib#763

MOPAC: adding file attached to issue cclib/cclib#763

---

Gaussian/Gaussian16/issue851.log
regressionfiles.txt

Add output file from cclib/cclib#851. This will need to be added in cclib/cclib#864

Add output file from issue 851

---

ORCA/ORCA4.2/947.out
regressionfiles.txt

The associated main PR is https://github.com/cclib/cclib/pull/951.

ORCA: constrained geom opt has an extra line before gradients

---

QChem/QChem5.2/qchem_tddft_rpa.out
QChem/QChem5.3/tddft.out
regressionfiles.txt

added regression files for issue https://github.com/cclib/cclib/issues/974

test cases for issue #974

---

FChk/README.md

Needed to get https://github.com/cclib/cclib/pull/953 to pass.

FChk: stub directory so regression passes

---

ORCA/ORCA4.2/casscf.out
regressionfiles.txt

Test data related to https://github.com/cclib/cclib/pull/1044

orca multiblock casscf fix

---

QChem/QChem5.2/HSO2F_TS.out
regressionfiles.txt

Output file from https://github.com/cclib/cclib/issues/871. It's safe to go in before the matching code PR.

QChem: add frequency->TS->frequency output

---

Gaussian/Gaussian16/H3_natcharge.log
regressionfiles.txt

Output file from cclib/cclib#1055.

Add log file corresponding to cclib/cclib#1055

---

Gaussian/Gaussian16/issue1153.log
regressionfiles.txt

The failing file from https://github.com/cclib/cclib/issues/1153.
This PR needs to go in *after* whatever PR fixes the issue.

Gaussian: file with pop=regular that runs past MO coefficients

---

Gaussian/Gaussian16/water.log

…g output with MO coefficients

Regression test file for #1153: error on parsing Gaussian mocoefs

---

regressionfiles.txt

Add missing file to regressionfiles.txt

---

Turbomole/Turbomole7.5/encoding/define (copy).out
Turbomole/Turbomole7.5/encoding/define.out
regressionfiles.txt

For `--multi` parsing that fails when non-utf8 encoding is used

Added regression test for #1174

---

QChem/QChem5.1/old_final_print_1.out
regressionfiles.txt

Referenced as part of [cclib/cclib@`bcc028f` (#732)](https://github.com/cclib/cclib/pull/732/commits/bcc028f7abd6e1e77d58de93fe96ab95e1220908) but never added.

Add file missing from https://github.com/cclib/cclib/pull/732

---

ORCA/ORCA4.2/a_DLPNO.txt
regressionfiles.yaml

File from https://github.com/cclib/cclib/issues/1092

Regression for 1369

---

Gaussian/Gaussian16/mp2_avdz_freq_tight.log
regressionfiles.yaml

This cannot be merged until the fix for https://github.com/cclib/cclib/issues/1290 is done.

Gaussian: MP2 frequencies

---

regressionfiles.yaml

Mutually dependent on https://github.com/cclib/cclib/pull/1405.

Parse energies as sensible units

---

Gaussian/Gaussian16/co_pbe1pbe_631ppGss.log
regressionfiles.yaml

From https://github.com/cclib/cclib/issues/1420
Requires https://github.com/cclib/cclib/pull/1452 to be merged first

Gaussian: file that broke platform parsing

---

Gaussian/Gaussian16/Pyridine_opt-eomccsd.log
ORCA/ORCA5.0/Benzene_opt_etsyms.log
regressionfiles.yaml

- Gaussian EOM-CCSD: a problem in mpenergies
- Orca TD-DFT: missing etsyms

Regression files for some optimised excited states calcs

---

Jaguar/Jaguar7.8/911.out
regressionfiles.yaml

Output file from https://github.com/cclib/cclib/issues/911
This needs to be merged after https://github.com/cclib/cclib/pull/1500.

Jaguar: vibrational output with 6 (or fewer) modes

---

NWChem/NWChem7.2/1518.out
regressionfiles.yaml

This needs to be merged after https://github.com/cclib/cclib/pull/1519.

NWChem: add file from https://github.com/cclib/cclib/issues/1518

---

QChem/QChem6.1/td_bnparaben+h.out
regressionfiles.yaml

...that caused a str.split() to break.  From https://github.com/cclib/cclib/issues/1573

QChem: TDDFT calculation with 100 states

---

Gaussian/Gaussian16/1615.gjf
Gaussian/Gaussian16/1615.log
regressionfiles.yaml

From https://github.com/cclib/cclib/issues/1615
Redo of #220 and #221

Gaussian: UCCSD(T) output with unexpected functional in metadata

---

regressionfiles.yaml

A follow-up to https://github.com/cclib/cclib-data/pull/233.  I had made the commit on that branch but forgot to push before merging...

Add ORCA/ORCA6.0/commercial_version.out to regressionfiles.yaml
