- DALTON/DALTON-2013.0/b3lyp_energy_dvb_sp_nosym.out
This is a regression file for an upcoming commit of a DALTON parser for cclib I've been working on. This is the standard dvb-molecule but handled without symmetry so there are no symmetry labels. Everything else parses fine.
It can be merged later when I manage to make the pull-request for the parser in the cclib repo. Hopefully it should not be long.
> DALTON: dvb without symmetry.

- Gaussian/Gaussian09/benzene_HPfreq.log
- Gaussian/Gaussian09/benzene_freq.log
- regression.py
- regressionfiles.txt
Added two separate regression tests, one testing for correct parsing of high-precision vib displacements from Gaussian09 (freq=hpmodes keyword), and another checking for correct parsing of low-precision vib displacements which are always printed in a freq calculation. cclib master can't currently parse high-precision displacements so will fail the tests, but the commits in https://github.com/cclib/cclib/pull/207/commits fix this.
> Tests: Gaussian09 low- & high-precision vib displ

- QChem/QChem4.2/CH3---Na+_RS_SCF_noprint.out
- QChem/QChem4.2/CH3---Na+_RS_noprint.out
- QChem/QChem4.2/CH4---Na+_noprint.out
- QChem/QChem4.2/print_frgm_false_opt.out
- QChem/QChem4.2/print_frgm_false_sp.out
- QChem/QChem4.2/print_frgm_true_opt.out
- QChem/QChem4.2/print_frgm_true_sp.out
- QChem/QChem4.2/print_frgm_true_sp_ccsdt.out
- QChem/QChem4.2/read_molecule.out
- regression.py
- regressionfiles.txt
These tests ensure that only the supersystem in a fragment-based calculation is parsed, regardless of whether or not the fragment sections are printed.
Also ensures the charge/multiplicity are handled properly, calculating them from number of electrons and atomic number rather than reading them from the user input.
> Q-Chem: fix charge/mult and fragment/supsersystem parsing

- regressionfiles.txt
> ORCA: adding example PES scan that fails due to an assert

- ADF/ADF2016/fa2.adf.out
- regression.py
- regressionfiles.txt
See cclib/cclib#275 for Felix's fix. Although it doesn't fix our current unit test, it does parse `atombasis` without symmetry, which is what this regression checks.
> ADF: add fa2 from Felix and a regression test for atombasis

- regression.py
This is a fix for the regression test added in https://github.com/cclib/cclib-data/pull/32.
> range() in Python 3 doesn't create a list

- regression.py
This is a follow up to cclib/cclib#393 and cclib/cclib#397 and needs to be merged before cclib/cclib#402
> Loosen precision on some old ORCA IR unit tests.

- ORCA/ORCA4.0/IrCl6_sp.out
- regression.py
- regressionfiles.txt
Some spaces were missed in the ORCA SCF output. This would occasionally cause problems when there were large changes in the SCF (as often happens for the first few steps when utilizing an ECP).
> Adds ORCA4.0 output with ECP and abnormal SCF values.

- regression.py
See https://github.com/cclib/cclib-data/pull/61#discussion_r132305255.
> ORCA: add additional case for bad SCF printing (#61)

- regression.py
- regressionfiles.txt
Contains the output given to us in https://github.com/cclib/cclib/pull/349. I'm not sure if this should be labeled as a bug, since it also catches a weird input error I mentioned in the PR.
The main PR should be merged before this one.
> QChem: fixed-width MO coefficient blocks and incomplete user input

- ORCA/ORCA4.0/CO2_freqs.out
- regressionfiles.txt
Reverts cclib/cclib-data#70 which effectively merges #66 back in. I believe this should be done only after cclib/cclib#425 is merged into the main repo, to avoid Travis failing.
> Un-revert "Adds linear molecule test case for ORCA."

- Turbomole/Turbomole/turbo
@ATenderholt @langner @berquist Here is the proper PR with just a blank directory for Turbomole files.
> Added empty directory for Turbomole files

- regressionfiles.txt
Regression data from cclib/cclib#629, courtesy of Felipe S. S. Schneider (@dudektria) needs to be submitted before cclib/cclib#630.
> Add ORCA example with mocoeffs glued together (from cclib/cclib#629)

- ORCA/ORCA4.0/comment_or_blank_line.out
- regressionfiles.txt
Coordinate input containing blank lines or comments is now parsed correctly
This relates to pull request 747 of cclib
> ORCA blank line or comment

- regressionfiles.txt
For https://github.com/cclib/cclib/issues/750.
This should go in _after_ https://github.com/cclib/cclib/pull/751.
> ORCA: PM3 geo opt that has a convergence termination line

- regressionfiles.txt
Reverts cclib/cclib-data#138 since it seems to have broken Travis: https://travis-ci.com/github/cclib/cclib/jobs/427553996
> Revert "Adding outputfile corresponding to issue 962"

- regressionfiles.txt
Reverts cclib/cclib-data#139 and re-adds the regression file - which needs to be merged in after the fix is in (or right before).
> Adding outputfile corresponding to issue 962

- NWChem/NWChem6.0/dvb_ir_hf.out
- regressionfiles.yaml
https://github.com/cclib/cclib/pull/1499 needs to be merged first.
Before a fix, https://github.com/cclib/cclib/commit/110292d71d4a88b3e1c2ec37c5fc95d4abf5b4b7 gives
$ ccget --list NWChem/NWChem6.0/dvb_ir_hf.out
Attempting to read NWChem/NWChem6.0/dvb_ir_hf.out
[NWChem NWChem/NWChem6.0/dvb_ir_hf.out ERROR] Encountered error when parsing.
[NWChem NWChem/NWChem6.0/dvb_ir_hf.out ERROR] Last line read:     3   3.97190D-14-2.57643D-15 1.69348D+01
Traceback (most recent call last):
File "/usr/bin/ccget", line 8, in <module>
sys.exit(ccget())
^^^^^^^
File "/usr/lib/python3.12/site-packages/cclib/scripts/ccget.py", line 182, in ccget
data = ccread(filename, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/cclib/io/ccio.py", line 185, in ccread
return log.parse() …
> NWChem: v6.0 with fixed-width mass-weighted Hessian

- regressionfiles.yaml
Follow-up to https://github.com/cclib/cclib-data/pull/204
> ORCA: change test classes used for pre-5 regressions

- ORCA/.gitignore
- ORCA/ORCA3.0/casscf_beryllium_atom_nosym.in
- ORCA/ORCA3.0/casscf_beryllium_atom_nosym.out
- ORCA/ORCA3.0/casscf_beryllium_atom_sym.in
- ORCA/ORCA3.0/casscf_beryllium_atom_sym.out
- ORCA/ORCA4.0/casscf_beryllium_atom_nosym.in
- ORCA/ORCA4.0/casscf_beryllium_atom_nosym.out
- ORCA/ORCA4.0/casscf_beryllium_atom_sym.in
- ORCA/ORCA4.0/casscf_beryllium_atom_sym.out
- ORCA/ORCA4.1/casscf_beryllium_atom_nosym.in
- ORCA/ORCA4.1/casscf_beryllium_atom_nosym.out
- ORCA/ORCA4.1/casscf_beryllium_atom_sym.in
- ORCA/ORCA4.1/casscf_beryllium_atom_sym.out
- ORCA/ORCA4.2/casscf_beryllium_atom_nosym.in
- ORCA/ORCA4.2/casscf_beryllium_atom_nosym.out
- ORCA/ORCA4.2/casscf_beryllium_atom_sym.in
- ORCA/ORCA4.2/casscf_beryllium_atom_sym.out
- ORCA/ORCA5.0/casscf_beryllium_atom_nosym.in
- ORCA/ORCA5.0/casscf_beryllium_atom_nosym.out
- ORCA/ORCA5.0/casscf_beryllium_atom_sym.in
- ORCA/ORCA5.0/casscf_beryllium_atom_sym.out
- ORCA/ORCA6.0/casscf_beryllium_atom_nosym.in
- ORCA/ORCA6.0/casscf_beryllium_atom_nosym.out
- ORCA/ORCA6.0/casscf_beryllium_atom_sym.in
- ORCA/ORCA6.0/casscf_beryllium_atom_sym.out
- regressionfiles.yaml
From cclib/cclib#1577
Also adds, for each ORCA program version, CASSCF calculations with and without symmetry on the beryllium atom.  Beryllium is a good example because the ground state should be ~90% the closed shell configuration ($\mathrm{1s^22s^2}$) and ~3.333...% each of the doubly-excited configurations into the degenerate p orbitals ($\mathrm{1s^22p_{x}^2}$, $\mathrm{1s^22p_{y}^2}$, and $\mathrm{1s^22p_{z}^2}$), which looks like
```
---------------------------------------------
CAS-SCF STATES FOR BLOCK  0 MULT= 1 IRREP= Ag NROOTS= 1
---------------------------------------------
ROOT   0:  E=     -14.6164970082 Eh
0.90188 [     0]: 2000
0.03271 [     1]: 0200
0.03271 [     3]: 0002
0.03271 [     2]: 0020
```
This could probably become a standard unit test in the future.
> ORCA: add CASSCF relaxed scan

- regressionfiles.yaml
Required for https://github.com/cclib/cclib/pull/1601
> ORCA: pre-4.1 geometry optimizations missing rotational constants

- ORCA/ORCA5.0/1177.out
- regressionfiles.yaml
From https://github.com/cclib/cclib/issues/1177 and https://github.com/ezpzbz/aiida-orca/pull/67
This won't parse without a fix.
> ORCA: add unrestricted geometry optimization with miniprint

- ORCA/ORCA5.0/1038.in
- ORCA/ORCA5.0/1038.out
- regressionfiles.yaml
File from https://github.com/cclib/cclib/issues/1038
This doesn't parse without a fix.
> ORCA: z-matrix generates placeholder atoms

- .envrc
- .github/workflows/ci.yml
- .github/workflows/nix.yml
- .github/workflows/pre-commit.yml
- .gitignore
- .pre-commit-config.yaml
- flake.lock
- flake.nix
- renovate.json
Added because I kept having problems with `ruamel.yaml` in my Python env, and this basically works.
> Add Nix for pre-commit dependencies

- DALTON/DALTON-2018/irc_point_nosym.dal
- DALTON/DALTON-2018/irc_point_nosym.out
- DALTON/DALTON-2018/irc_point_sym.dal
- DALTON/DALTON-2018/irc_point_sym.out
- regressionfiles.yaml
These aren't regressions, since there's nothing here that parses but to incorrect values, but are
- additional test case references for the principal moment of inertia
- updates needed for more precise rotational constant testing
> Updates for increased rotational constant testing

- ORCA/ORCA6.0/commercial_version.out
_cf._ cclib/cclib#1640
This PR adds a simple example output from a commercial version of ORCA which have suffix `-f.N` after its release version.
> ORCA: output from a commercial version
